[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
serde_json = "1.0.140"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
