/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoadScenarioImport } from './routes/load-scenario'
import { Route as EditorImport } from './routes/editor'
import { Route as IndexImport } from './routes/index'
import { Route as SessionSessionIdImport } from './routes/session/$sessionId'

// Create/Update Routes

const LoadScenarioRoute = LoadScenarioImport.update({
  id: '/load-scenario',
  path: '/load-scenario',
  getParentRoute: () => rootRoute,
} as any)

const EditorRoute = EditorImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SessionSessionIdRoute = SessionSessionIdImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorImport
      parentRoute: typeof rootRoute
    }
    '/load-scenario': {
      id: '/load-scenario'
      path: '/load-scenario'
      fullPath: '/load-scenario'
      preLoaderRoute: typeof LoadScenarioImport
      parentRoute: typeof rootRoute
    }
    '/session/$sessionId': {
      id: '/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/load-scenario': typeof LoadScenarioRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/load-scenario': typeof LoadScenarioRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/load-scenario': typeof LoadScenarioRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/editor' | '/load-scenario' | '/session/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/editor' | '/load-scenario' | '/session/$sessionId'
  id: '__root__' | '/' | '/editor' | '/load-scenario' | '/session/$sessionId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditorRoute: typeof EditorRoute
  LoadScenarioRoute: typeof LoadScenarioRoute
  SessionSessionIdRoute: typeof SessionSessionIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorRoute: EditorRoute,
  LoadScenarioRoute: LoadScenarioRoute,
  SessionSessionIdRoute: SessionSessionIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/editor",
        "/load-scenario",
        "/session/$sessionId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/editor": {
      "filePath": "editor.tsx"
    },
    "/load-scenario": {
      "filePath": "load-scenario.tsx"
    },
    "/session/$sessionId": {
      "filePath": "session/$sessionId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
